apiVersion: apps/v1
kind: Deployment
metadata:
  name: xgboost-api-deployment
  namespace: xgboost-service
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: xgboost-api
  template:
    metadata:
      labels:
        app: xgboost-api
    spec:
      containers:
      - name: xgboost-api
        image: dianazawislak/xgboost-api:latest  # Ensure this is the correct image
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: "/mnt/block_storage"
          name: xgboost-model-storage
        resources:
          requests:
            memory: "500Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: xgboost-model-storage
        persistentVolumeClaim:
          claimName: xgboost-model-pvc
