apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-script
  namespace: xgboost-service
data:
  init.js: |
    db = db.getSiblingDB('admin');
    db.createUser({
      user: process.env.MONGO_INITDB_ROOT_USERNAME,
      pwd: process.env.MONGO_INITDB_ROOT_PASSWORD,
      roles: [
        { role: "userAdminAnyDatabase", db: "admin" },
        { role: "readWriteAnyDatabase", db: "admin" },
        { role: "dbAdminAnyDatabase", db: "admin" }
      ]
    });
    db = db.getSiblingDB('rentals');
    db.createCollection('zip_33131');