apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: xgboost-service
data:
  hosts.toml: |
    server = "https://157.245.3.167:5000"
    [host."https://157.245.3.167:5000"]
      capabilities = ["pull", "resolve"]
      skip_verify = true
  registry.crt: |
    [plugins."io.containerd.grpc.v1.cri".registry.configs."157.245.3.167:5000".tls]
      insecure_skip_verify = true