apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xgboost-model-training-pvc
  namespace: xgboost-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
