---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: xgboost-service
spec:
  selector:
    matchLabels:
      app: registry
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: registry-storage
              mountPath: /var/lib/registry
      volumes:
        - name: registry-storage
          persistentVolumeClaim:
            claimName: registry-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: xgboost-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: xgboost-service
spec:
  type: LoadBalancer  # Exposes the registry publicly for external access
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
