apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
  namespace: xgboost-service
spec:
  containers:
  - name: xgboost-api
    image: 157.245.3.167:5000/xgboost-api:latest
    imagePullPolicy: Always
  - name: xgboost-training
    image: 157.245.3.167:5000/xgboost-training:latest
    imagePullPolicy: Always
  imagePullSecrets:
  - name: regcred
