apiVersion: batch/v1
kind: Job
metadata:
  name: xgboost-training-job-007
  namespace: xgboost-service
spec:
  template:
    spec:
      containers:
      - name: xgboost-training
        image: 157.245.3.167:5000/xgboost-training:latest
        imagePullPolicy: Always
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: MONGO_URI
        volumeMounts:
        - name: model-storage
          mountPath: /app/models
        - name: registry-config
          mountPath: /etc/containerd/certs.d/157.245.3.167:5000
        - name: registry-config
          mountPath: /etc/docker/certs.d/157.245.3.167:5000
          subPath: registry.crt
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: xgboost-model-pvc
      - name: registry-config
        configMap:
          name: registry-config
      restartPolicy: Never
  backoffLimit: 4