apiVersion: apps/v1
kind: Deployment
metadata:
  name: xgboost-api-deployment
  namespace: xgboost-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xgboost-api
  template:
    metadata:
      labels:
        app: xgboost-api
    spec:
      containers:
      - name: xgboost-api
        image: 174.138.118.179:5000/xgboost-api:latest
        command: ["python"]
        args: ["app.py"]  # Make sure this matches your API script name
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: "/mnt/block_storage"
          name: xgboost-model-storage
        resources:
          requests:
            memory: "500Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: MONGO_PASSWORD
        - name: MONGODB_HOST
          value: "159.65.167.68"  # MongoDB router IP
      volumes:
      - name: xgboost-model-storage
        persistentVolumeClaim:
          claimName: xgboost-model-pvc